http:
  routers:
    APPNAME-PLACEHOLDER-rtr:
      rule: "Host(`APP-SUBDOMAIN-PLACEHOLDER.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        # - websecure-external
        # - websecure-internal
      middlewares:
        - CHAIN-PLACEHOLDER
      service: APPNAME-PLACEHOLDER-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    APPNAME-PLACEHOLDER-svc:
      loadBalancer:
        servers:
          - url: "APP-URL-PLACEHOLDER" # http://IP-ADDRESS:PORT