services:
  # Calibre-Web - Browse, Read and Download eBooks
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$CALIBREWEB_PORT:8083" 
    volumes:
      - $DOCKERDIR/appdata/calibre-web:/config
      - $BOOKSDIR:/data/books
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DOCKER_MODS: linuxserver/mods:universal-calibre #optional
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1 #optional
    # DOCKER-LABELS-PLACEHOLDER