services:
  # Organizr - Homelab Dashboard
  organizr:
    image: ghcr.io/organizr/organizr
    container_name: organizr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$ORGANIZR_PORT:80" 
    volumes:
      - $DOCKERDIR/appdata/organizr:/config
    environment:
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER