services:
  # PostgreSQL - Database
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      - default
    ports:
      - "$POSTGRESQL_PORT:5432"
    volumes:
      - $DOCKERDIR/appdata/postgresql:/var/lib/postgresql/data
    environment:
      # - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_default_password
    secrets:
      - postgres_default_password