services:
  # Remmina - Remote Desktop Client
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
    # DEVICES-GPU-PLACEHOLDER-DO-NOT-DELETE
    ports:
      - "$REMMINA_PORT:3000" 
      # - "3001:3001" # HTTPS
    volumes:
      - $DOCKERDIR/appdata/remmina:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # DRINODE: /dev/dri/renderD128 
    # DOCKER-LABELS-PLACEHOLDER